### ISSUE TITLE
The test project is no longer working properly.

### ISSUE THREAD

**Issue by LLLLLayer** [ShenghaiWang/SwiftLlama#18]
https://github.com/ggerganov/llama.cpp/issues/10747
![Image](https://github.com/user-attachments/assets/700ac948-53df-4e98-99ce-7d4601b0303f)

**Comment by LLLLLayer** [comment]
The latest version of llama has been fixed.Thanks!

**Comment by pgorzelany** [comment]
How was it fixed? I am still facing this issue when trying to add llama.cpp as a swift package.

**Comment by Linorman** [comment]
I faced this problem as well, have you figured out this problem?

> How was it fixed? I am still facing this issue when trying to add llama.cpp as a swift package.
